export const colors = {
  deepEmerald: "#123D33",
  darkEmerald: "#082B24",
  teal: "#1E5A4C",
  ivory: "#F7F5EF",
  sand: "#E8E2D6",
  surface: "#FFFEFA",
  surfaceElevated: "#FFFFFF",
  surfaceMuted: "#F0F3EF",
  gold: "#B58A3C",
  goldMuted: "#E8D9B8",
  sage: "#718D7F",
  text: "#17211E",
  textStrong: "#0D1814",
  secondary: "#5D6964",
  textMuted: "#68756F",
  border: "#D7DDD8",
  borderStrong: "#B9C7C0",
  success: "#236B46",
  successSurface: "#E8F4ED",
  warning: "#815713",
  warningSurface: "#FAF1DD",
  danger: "#A23E3E",
  dangerSurface: "#FBECEC",
  info: "#285F79",
  infoSurface: "#EAF3F7",
  overlay: "rgba(8, 43, 36, 0.56)",
} as const;

export const roleLabels = {
  system_admin: "System Admin",
  president: "President",
  vice_president: "Vice President",
  secretary: "Secretary",
  finance: "Finance",
  auditor: "Auditor",
  committee_member: "Committee Member",
  member: "Member",
} as const;
