-- Masjid-e-Mamoor
-- Migration 002: V1 authorization permission catalogue
-- Seeds permission vocabulary and role-level grants.
-- RLS predicates and trusted-operation enforcement remain separate.

begin;

insert into public.permissions (key, name, description)
values
    ('identity.profile.read', 'Identity / Profile / Read', 'Read the caller''s authorized application profile'),
    ('identity.profile.update', 'Identity / Profile / Update', 'Update the caller''s permitted profile fields'),
    ('administration.users.manage', 'Administration / Users / Manage', 'Manage application-user administration through authorized workflows'),
    ('administration.roles.assign', 'Administration / Roles / Assign', 'Assign an approved application role through an authorized workflow'),
    ('administration.permissions.manage', 'Administration / Permissions / Manage', 'Manage role-permission administration through an authorized workflow'),
    ('membership.members.read', 'Membership / Members / Read', 'Read member information within authorized scope'),
    ('membership.members.create', 'Membership / Members / Create', 'Create member records through an authorized workflow'),
    ('membership.members.update', 'Membership / Members / Update', 'Update member records within authorized scope'),
    ('membership.referrals.create', 'Membership / Referrals / Create', 'Create authorized referral registrations'),
    ('membership.lifecycle.read', 'Membership / Lifecycle / Read', 'Read membership lifecycle/history within authorized scope'),
    ('donations.obligations.read', 'Donations / Obligations / Read', 'Read donation obligations within authorized scope'),
    ('donations.payments.create', 'Donations / Payments / Create', 'Submit/create payment records within authorized scope'),
    ('donations.payments.proof_upload', 'Donations / Payments / Proof Upload', 'Upload payment proof within authorized scope'),
    ('donations.payments.verify', 'Donations / Payments / Verify', 'Verify payment through the trusted financial workflow'),
    ('donations.payments.allocate', 'Donations / Payments / Allocate', 'Allocate a verified payment through the trusted allocation workflow'),
    ('donations.obligations.manage', 'Donations / Obligations / Manage', 'Manage donation obligations through authorized workflows'),
    ('donations.additional.create', 'Donations / Additional / Create', 'Record an additional donation within authorized scope'),
    ('donations.anonymous.create', 'Donations / Anonymous / Create', 'Record an anonymous donation through an authorized workflow'),
    ('donations.jummah.create', 'Donations / Jummah / Create', 'Record Jummah cash donation through an authorized workflow'),
    ('donations.reports.read', 'Donations / Reports / Read', 'Read donation reports within authorized scope'),
    ('finance.accounts.read', 'Finance / Accounts / Read', 'Read authorized financial accounts'),
    ('finance.accounts.manage', 'Finance / Accounts / Manage', 'Manage financial accounts through authorized workflows'),
    ('finance.transactions.read', 'Finance / Transactions / Read', 'Read authorized financial transactions'),
    ('finance.transfers.create', 'Finance / Transfers / Create', 'Create financial transfers'),
    ('finance.transfers.approve', 'Finance / Transfers / Approve', 'Approve/verify transfers subject to maker/checker rules'),
    ('finance.expenses.create', 'Finance / Expenses / Create', 'Create/submit expenses'),
    ('finance.expenses.approve', 'Finance / Expenses / Approve', 'Approve expenses subject to maker/checker rules'),
    ('finance.corrections.create', 'Finance / Corrections / Create', 'Initiate authorized financial corrections'),
    ('finance.cancellations.create', 'Finance / Cancellations / Create', 'Initiate authorized financial cancellations/reversals'),
    ('finance.reconciliation.manage', 'Finance / Reconciliation / Manage', 'Perform authorized financial reconciliation'),
    ('finance.reports.read', 'Finance / Reports / Read', 'Read authorized financial reports'),
    ('finance.proofs.read', 'Finance / Proofs / Read', 'Read authorized financial proofs and bills'),
    ('committee.tasks.read', 'Committee / Tasks / Read', 'Read assigned/authorized committee tasks'),
    ('committee.tasks.manage', 'Committee / Tasks / Manage', 'Manage authorized committee tasks'),
    ('committee.tasks.assign', 'Committee / Tasks / Assign', 'Assign committee tasks'),
    ('committee.meetings.read', 'Committee / Meetings / Read', 'Read authorized meeting information'),
    ('committee.meetings.manage', 'Committee / Meetings / Manage', 'Manage authorized meetings'),
    ('committee.attendance.record', 'Committee / Attendance / Record', 'Record authorized committee/meeting attendance'),
    ('attendance.records.read', 'Attendance / Records / Read', 'Read attendance records within authorized scope'),
    ('attendance.records.create', 'Attendance / Records / Create', 'Create attendance records within authorized scope'),
    ('attendance.records.manage', 'Attendance / Records / Manage', 'Manage/correct attendance through authorized workflows'),
    ('attendance.offline_sync', 'Attendance / Offline Sync', 'Submit authorized offline attendance operations for server validation'),
    ('notifications.own.read', 'Notifications / Own / Read', 'Read the caller''s notifications'),
    ('notifications.preferences.manage', 'Notifications / Preferences / Manage', 'Manage the caller''s notification preferences'),
    ('notifications.admin.manage', 'Notifications / Admin / Manage', 'Perform authorized administrative notification management'),
    ('reports.operational.read', 'Reports / Operational / Read', 'Read authorized operational reports'),
    ('reports.membership.read', 'Reports / Membership / Read', 'Read authorized membership reports'),
    ('reports.donations.read', 'Reports / Donations / Read', 'Read authorized donation reports'),
    ('reports.finance.read', 'Reports / Finance / Read', 'Read authorized financial reports'),
    ('reports.audit.read', 'Reports / Audit / Read', 'Read authorized audit reports'),
    ('audit.records.read', 'Audit / Records / Read', 'Read audit records within authorized oversight scope')
on conflict (key) do update
set name = excluded.name,
    description = excluded.description;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from (
values
    ('president', 'identity.profile.read'),
    ('vice_president', 'identity.profile.read'),
    ('secretary', 'identity.profile.read'),
    ('finance', 'identity.profile.read'),
    ('auditor', 'identity.profile.read'),
    ('committee_member', 'identity.profile.read'),
    ('member', 'identity.profile.read'),
    ('president', 'identity.profile.update'),
    ('vice_president', 'identity.profile.update'),
    ('secretary', 'identity.profile.update'),
    ('finance', 'identity.profile.update'),
    ('auditor', 'identity.profile.update'),
    ('committee_member', 'identity.profile.update'),
    ('member', 'identity.profile.update'),
    ('president', 'administration.users.manage'),
    ('president', 'administration.roles.assign'),
    ('president', 'administration.permissions.manage'),
    ('president', 'membership.members.read'),
    ('vice_president', 'membership.members.read'),
    ('secretary', 'membership.members.read'),
    ('finance', 'membership.members.read'),
    ('auditor', 'membership.members.read'),
    ('committee_member', 'membership.members.read'),
    ('member', 'membership.members.read'),
    ('president', 'membership.members.create'),
    ('secretary', 'membership.members.create'),
    ('president', 'membership.members.update'),
    ('secretary', 'membership.members.update'),
    ('president', 'membership.referrals.create'),
    ('vice_president', 'membership.referrals.create'),
    ('secretary', 'membership.referrals.create'),
    ('committee_member', 'membership.referrals.create'),
    ('president', 'membership.lifecycle.read'),
    ('vice_president', 'membership.lifecycle.read'),
    ('secretary', 'membership.lifecycle.read'),
    ('finance', 'membership.lifecycle.read'),
    ('auditor', 'membership.lifecycle.read'),
    ('committee_member', 'membership.lifecycle.read'),
    ('member', 'membership.lifecycle.read'),
    ('president', 'donations.obligations.read'),
    ('vice_president', 'donations.obligations.read'),
    ('secretary', 'donations.obligations.read'),
    ('finance', 'donations.obligations.read'),
    ('auditor', 'donations.obligations.read'),
    ('committee_member', 'donations.obligations.read'),
    ('member', 'donations.obligations.read'),
    ('president', 'donations.payments.create'),
    ('vice_president', 'donations.payments.create'),
    ('secretary', 'donations.payments.create'),
    ('finance', 'donations.payments.create'),
    ('committee_member', 'donations.payments.create'),
    ('member', 'donations.payments.create'),
    ('president', 'donations.payments.proof_upload'),
    ('vice_president', 'donations.payments.proof_upload'),
    ('secretary', 'donations.payments.proof_upload'),
    ('finance', 'donations.payments.proof_upload'),
    ('committee_member', 'donations.payments.proof_upload'),
    ('member', 'donations.payments.proof_upload'),
    ('president', 'donations.payments.verify'),
    ('vice_president', 'donations.payments.verify'),
    ('finance', 'donations.payments.verify'),
    ('president', 'donations.payments.allocate'),
    ('vice_president', 'donations.payments.allocate'),
    ('finance', 'donations.payments.allocate'),
    ('president', 'donations.obligations.manage'),
    ('secretary', 'donations.obligations.manage'),
    ('finance', 'donations.obligations.manage'),
    ('president', 'donations.additional.create'),
    ('vice_president', 'donations.additional.create'),
    ('secretary', 'donations.additional.create'),
    ('finance', 'donations.additional.create'),
    ('committee_member', 'donations.additional.create'),
    ('member', 'donations.additional.create'),
    ('president', 'donations.anonymous.create'),
    ('finance', 'donations.anonymous.create'),
    ('president', 'donations.jummah.create'),
    ('vice_president', 'donations.jummah.create'),
    ('secretary', 'donations.jummah.create'),
    ('finance', 'donations.jummah.create'),
    ('committee_member', 'donations.jummah.create'),
    ('president', 'donations.reports.read'),
    ('vice_president', 'donations.reports.read'),
    ('secretary', 'donations.reports.read'),
    ('finance', 'donations.reports.read'),
    ('auditor', 'donations.reports.read'),
    ('member', 'donations.reports.read'),
    ('president', 'finance.accounts.read'),
    ('vice_president', 'finance.accounts.read'),
    ('finance', 'finance.accounts.read'),
    ('auditor', 'finance.accounts.read'),
    ('president', 'finance.accounts.manage'),
    ('finance', 'finance.accounts.manage'),
    ('president', 'finance.transactions.read'),
    ('vice_president', 'finance.transactions.read'),
    ('finance', 'finance.transactions.read'),
    ('auditor', 'finance.transactions.read'),
    ('president', 'finance.transfers.create'),
    ('vice_president', 'finance.transfers.create'),
    ('finance', 'finance.transfers.create'),
    ('president', 'finance.transfers.approve'),
    ('vice_president', 'finance.transfers.approve'),
    ('finance', 'finance.transfers.approve'),
    ('president', 'finance.expenses.create'),
    ('vice_president', 'finance.expenses.create'),
    ('finance', 'finance.expenses.create'),
    ('president', 'finance.expenses.approve'),
    ('vice_president', 'finance.expenses.approve'),
    ('finance', 'finance.expenses.approve'),
    ('president', 'finance.corrections.create'),
    ('vice_president', 'finance.corrections.create'),
    ('finance', 'finance.corrections.create'),
    ('president', 'finance.cancellations.create'),
    ('vice_president', 'finance.cancellations.create'),
    ('finance', 'finance.cancellations.create'),
    ('president', 'finance.reconciliation.manage'),
    ('finance', 'finance.reconciliation.manage'),
    ('president', 'finance.reports.read'),
    ('vice_president', 'finance.reports.read'),
    ('finance', 'finance.reports.read'),
    ('auditor', 'finance.reports.read'),
    ('president', 'finance.proofs.read'),
    ('vice_president', 'finance.proofs.read'),
    ('finance', 'finance.proofs.read'),
    ('auditor', 'finance.proofs.read'),
    ('president', 'committee.tasks.read'),
    ('vice_president', 'committee.tasks.read'),
    ('secretary', 'committee.tasks.read'),
    ('auditor', 'committee.tasks.read'),
    ('committee_member', 'committee.tasks.read'),
    ('president', 'committee.tasks.manage'),
    ('vice_president', 'committee.tasks.manage'),
    ('secretary', 'committee.tasks.manage'),
    ('committee_member', 'committee.tasks.manage'),
    ('president', 'committee.tasks.assign'),
    ('vice_president', 'committee.tasks.assign'),
    ('secretary', 'committee.tasks.assign'),
    ('president', 'committee.meetings.read'),
    ('vice_president', 'committee.meetings.read'),
    ('secretary', 'committee.meetings.read'),
    ('auditor', 'committee.meetings.read'),
    ('committee_member', 'committee.meetings.read'),
    ('president', 'committee.meetings.manage'),
    ('vice_president', 'committee.meetings.manage'),
    ('secretary', 'committee.meetings.manage'),
    ('committee_member', 'committee.meetings.manage'),
    ('president', 'committee.attendance.record'),
    ('vice_president', 'committee.attendance.record'),
    ('secretary', 'committee.attendance.record'),
    ('committee_member', 'committee.attendance.record'),
    ('president', 'attendance.records.read'),
    ('vice_president', 'attendance.records.read'),
    ('secretary', 'attendance.records.read'),
    ('auditor', 'attendance.records.read'),
    ('committee_member', 'attendance.records.read'),
    ('member', 'attendance.records.read'),
    ('president', 'attendance.records.create'),
    ('vice_president', 'attendance.records.create'),
    ('secretary', 'attendance.records.create'),
    ('committee_member', 'attendance.records.create'),
    ('member', 'attendance.records.create'),
    ('president', 'attendance.records.manage'),
    ('vice_president', 'attendance.records.manage'),
    ('secretary', 'attendance.records.manage'),
    ('committee_member', 'attendance.records.manage'),
    ('president', 'attendance.offline_sync'),
    ('vice_president', 'attendance.offline_sync'),
    ('secretary', 'attendance.offline_sync'),
    ('committee_member', 'attendance.offline_sync'),
    ('member', 'attendance.offline_sync'),
    ('president', 'notifications.own.read'),
    ('vice_president', 'notifications.own.read'),
    ('secretary', 'notifications.own.read'),
    ('finance', 'notifications.own.read'),
    ('auditor', 'notifications.own.read'),
    ('committee_member', 'notifications.own.read'),
    ('member', 'notifications.own.read'),
    ('president', 'notifications.preferences.manage'),
    ('vice_president', 'notifications.preferences.manage'),
    ('secretary', 'notifications.preferences.manage'),
    ('finance', 'notifications.preferences.manage'),
    ('auditor', 'notifications.preferences.manage'),
    ('committee_member', 'notifications.preferences.manage'),
    ('member', 'notifications.preferences.manage'),
    ('president', 'notifications.admin.manage'),
    ('vice_president', 'notifications.admin.manage'),
    ('secretary', 'notifications.admin.manage'),
    ('finance', 'notifications.admin.manage'),
    ('president', 'reports.operational.read'),
    ('vice_president', 'reports.operational.read'),
    ('secretary', 'reports.operational.read'),
    ('finance', 'reports.operational.read'),
    ('auditor', 'reports.operational.read'),
    ('committee_member', 'reports.operational.read'),
    ('member', 'reports.operational.read'),
    ('president', 'reports.membership.read'),
    ('vice_president', 'reports.membership.read'),
    ('secretary', 'reports.membership.read'),
    ('finance', 'reports.membership.read'),
    ('auditor', 'reports.membership.read'),
    ('committee_member', 'reports.membership.read'),
    ('member', 'reports.membership.read'),
    ('president', 'reports.donations.read'),
    ('vice_president', 'reports.donations.read'),
    ('secretary', 'reports.donations.read'),
    ('finance', 'reports.donations.read'),
    ('auditor', 'reports.donations.read'),
    ('member', 'reports.donations.read'),
    ('president', 'reports.finance.read'),
    ('vice_president', 'reports.finance.read'),
    ('finance', 'reports.finance.read'),
    ('auditor', 'reports.finance.read'),
    ('president', 'reports.audit.read'),
    ('auditor', 'reports.audit.read'),
    ('president', 'audit.records.read'),
    ('finance', 'audit.records.read'),
    ('auditor', 'audit.records.read')
) as grants(role_key, permission_key)
join public.roles r on r.key = grants.role_key
join public.permissions p on p.key = grants.permission_key
on conflict (role_id, permission_id) do nothing;

commit;
